name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 1:00 PM UTC (12:00 AM AEDT)
    - cron: "0 13 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          BLOCKS: â–‘â–’â–“â–ˆ
          CODE_LANG: "txt\nðŸ’¬ Language statistics this week:" # optional
          TIME_RANGE: last_7_days
          LANG_COUNT: 7
          SHOW_TIME: true
          SHOW_TOTAL: false
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: false
          COMMIT_MESSAGE: update language statistics
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: 6ruby1
          AUTHOR_EMAIL: ruby@rubygem.dev
