name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 12:00 AM UTC (11:00 AM AEDT)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: â–‘â–’â–“â–ˆ
          CODE_LANG: "txt\nðŸ’¬ Language statistics this week:"
          TIME_RANGE: last_7_days
          SHOW_TITLE: true
          LANG_COUNT: 14
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true #NOTE: overrides SHOW_TOTAL
          STOP_AT_OTHER: true
          COMMIT_MESSAGE: update language statistics
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: 6ruby1
          AUTHOR_EMAIL: ruby@rubygem.dev
